package Controller;

public interface Constants {
    int MAIN_MENU_STUDENT = 1;
    int MAIN_MENU_LIBRARIAN = 2;
    int MAIN_MENU_EXIT = 3;

    int STUDENT_MENU_SHOW_ALL_BOOKS = 1;
    int STUDENT_MENU_BORROW_BOOKS = 2;
    int STUDENT_MENU_RETURN_BOOKS = 3;
    int STUDENT_MENU_BACK_TO_MAIN = 4;

    int LIBRARIAN_MENU_SHOW_ALL_BOOKS = 1;
    int LIBRARIAN_MENU_ADD_BOOKS = 2;
    int LIBRARIAN_MENU_DELETE_BOOKS = 3;
    int LIBRARIAN_MENU_UPDATE_BOOKS = 4;
    int LIBRARIAN_MENU_LIST_STUDENTS_BORROWING = 5;
    int LIBRARIAN_MENU_BACK_TO_MAIN = 6;
}
